project:
  type: website
  output-dir: _site
  resources:
    - styles.css
    - googlefcbd9973d8740692.html
    - CNAME

website:
  navbar:
    background: "#1a1c2c"
    container: true
    left:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: videos.qmd
        text: Videos
      - href: education.qmd
        text: Education
      - href: experience.qmd
        text: Experience
      - href: contact.qmd
        text: Contact
      - href: about.qmd
        text: About

format:
  html:
    theme: minimal
    css:
      - styles.css?v=10
    toc: false
    mainfont: "Inter"
    include-in-header:
      text: |
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
